
- name: Create Config files
  ansible.builtin.template:
    src: ../templates/{{ item.src }}
    dest: '{{ minio_etc_dir}}/{{ item.dst }}'
  loop:
    - { src: 'nginx.conf.j2', dst: 'minio-lb-nginx.conf'}
  become: yes
  

- name: Create systemd unit files
  ansible.builtin.template:
    src: ../templates/{{ item.src }}
    dest: /etc/systemd/system/{{ item.dst }}.service
  loop:
    - { src: 'loadbalancer_systemd.j2', dst: 'minio-lb'}
  become: yes 
  
# - name: Systemd Reload Daemons
#   shell: systemctl daemon-reload
  
- name: Enable MinIO loadbalancer systemd daemon
  systemd:
    name: minio-lb
    enabled: yes
    daemon_reload: true
  become: yes