# Create a non-Kerberos proxy to allow prometheus to scrape
# metrics from kerberos protected services

- name: Include Prometheis Impala Proxy Exporter
  include_tasks: prometheus-impala.yml
  
- name: Include Prometheus Node Exporter
  include_tasks: prometheus-node-exporter.yml
  
- name: Systemctl Reload Daemon
  shell: systemctl daemon-reload
  become: yes