- name: Check if Airflow db exists
  postgresql_query:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      query: >
        SELECT datname 
        FROM pg_database
        WHERE datname = '{{ airflow_db }}'
  delegate_to: localhost
  connection: local
  run_once: true
  
- name: Create Airflow db user
  postgresql_user:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      state: present
      name: "{{ airflow_db_user }}"
      password: "{{ airflow_db_password }}"
  delegate_to: localhost
  connection: local
  run_once: true

- name: Create Airflow database
  postgresql_db:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      owner: "{{ airflow_db_user }}"
      state: present
      name: "{{ airflow_db }}"
  delegate_to: localhost
  connection: local
  run_once: true

# Airflow schema will be created by Airflow during startup