- name: Create OS group
  ansible.builtin.group:
    name: "{{ ranger_sync_group_name }}"
    state: present
  become: yes
    
- name: Include Create OS user
  include_role:
    name: create-system-user
  vars:
    new_user: "{{ spark_os_user }}"
    new_group: "{{ ranger_sync_group_name }}"
  