- name: Debug info
  ansible.builtin.debug:
    msg: "{{ item.url }}"
  loop: '{{ spark_additional_libs_download_url| flatten }}'
  
- name: Check if libraries are already downloaded
  stat:
    path: "{{ download_root }}/{{ item.url | basename }}"
  register: stat_lib
  loop: '{{ spark_additional_libs_download_url| flatten }}'
  delegate_to: localhost
  connection: local
  
- name: Debug info
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ stat_lib.results| flatten }}"

- name: Download libraries
  get_url:
      url: "{{ item.item.url }}"
      dest: "{{ download_root }}/{{ item.item.url | basename }}"
  loop:
    - "{{ stat_lib.results| flatten }}"
  delegate_to: localhost
  connection: local
  when: item.stat.exists == False