{
 "title": "Service Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Impala Daemon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_impalad\", port=\"21050\"})"
    }
   ]
  },
  {
   "title": "Impala Statestore",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_statestored\"})"
    }
   ]
  },
  {
   "title": "Impala Catalog",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_catalogd\"})"
    }
   ]
  },
  {
   "title": "HDFS Namenode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_namenode\"})"
    }
   ]
  },
  {
   "title": "HDFS Datanode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_datanode\"})"
    }
   ]
  },
  {
   "title": "HDFS Journalnode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_journalnode\"})"
    }
   ]
  },
  {
   "title": "WebHDFS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_webhdfs\"})"
    }
   ]
  },
  {
   "title": "Yarn Resourcemanager",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_resourcemanager\"})"
    }
   ]
  },
  {
   "title": "Yarn Nodemanager",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_nodemanager\"})"
    }
   ]
  },
  {
   "title": "Yarn Timelineserver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_timelineserver\"})"
    }
   ]
  },
  {
   "title": "Hue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hue\"})"
    }
   ]
  },
  {
   "title": "Jupyterhub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"jupyterhub\"})"
    }
   ]
  },
  {
   "title": "Superset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"superset\"})"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"zookeeper\"})",
     "legendFormat": "Zookeeper"
    }
   ]
  },
  {
   "title": "Hive Metastore",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hive_metastore\"})"
    }
   ]
  },
  {
   "title": "Spark History",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"spark_history\"})"
    }
   ]
  },
  {
   "title": "Ranger",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"ranger\"})"
    }
   ]
  },
  {
   "title": "Solr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"solr\"})"
    }
   ]
  },
  {
   "title": "Livy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"livy\"})"
    }
   ]
  },
  {
   "title": "Kerberos KDC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"krb_kdc\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Impala",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_impalad\", port=\"21050\"})",
     "legendFormat": "Impalad"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_statestored\"})",
     "legendFormat": "Statestored"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"impala_catalogd\"})",
     "legendFormat": "Catalogd"
    }
   ]
  },
  {
   "title": "Hadoop - HDFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_journalnode\"})",
     "legendFormat": "Journalnode"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_namenode\"})",
     "legendFormat": "Namenode"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_webhdfs\"})",
     "legendFormat": "WebHDFS"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_zkfc\"})",
     "legendFormat": "Failovernode"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"hdfs_datanode\"})",
     "legendFormat": "Datanode"
    }
   ]
  },
  {
   "title": "Hadoop - Yarn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_resourcemanager\"})",
     "legendFormat": "Resourcemanager"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_timelineserver\"})",
     "legendFormat": "Timelineserver"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"yarn_nodemanager\"})",
     "legendFormat": "Nodemanager"
    }
   ]
  },
  {
   "title": "Analytics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hue\"})",
     "legendFormat": "Hue"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"jupyterhub\"})",
     "legendFormat": "Jupyterhub"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"superset\"})",
     "legendFormat": "Superset"
    }
   ]
  },
  {
   "title": "Hive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"hive_metastore\"})",
     "legendFormat": "Metastore"
    }
   ]
  },
  {
   "title": "Spark",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 27 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"spark_history\"})",
     "legendFormat": "Historyserver"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"livy\"})",
     "legendFormat": "Livy"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"zookeeper\"})",
     "legendFormat": "Zookeeper"
    }
   ]
  },
  {
   "title": "Ranger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 35 },
   "targets": [
    {
     "expr": "sum(cluster_service_port_up{name=\"ranger\"})",
     "legendFormat": "Ranger"
    },
    {
     "expr": "sum(cluster_service_port_up{name=\"solr\"})",
     "legendFormat": "Solr"
    }
   ]
  }
 ]
}