- name: Get user database
  getent:
    database: passwd
        
- name: Create Airflow configuration
  template:
    src: "../templates/{{ item.name }}"
    dest: "{{ airflow_etc_dir }}/{{ item.dest }}"
    mode: '0644'
  loop:
    - { name: 'airflow.env.j2', dest: 'airflow.env'}
    - { name: 'nginx-rev-proxy.conf.j2', dest: 'nginx-rev-proxy.conf'}
  become: yes
