- name: Create Airflow configuration
  template:
    src: "../templates/{{ item.name }}"
    dest: "{{ airflow_etc_dir }}/{{ item.dest }}"
    mode: '0644'
  loop:
    - { name: 'airflow-env.sh.j2', dest: 'airflow-env.sh'}
  become: yes