- name: Create Airflow configuration
  template:
    src: "../templates/{{ item.name }}"
    dest: "{{ airflow_etc_dir }}/{{ item.dest }}"
    mode: '0644'
  loop:
    - { name: 'airflow.env.j2', dest: 'airflow.env'}
  become: yes
  
  
- name: Create symlinks
  file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
  loop:
    - { "src": "{{ airflow_etc_dir }}/airflow.env", "dest": "{{ airflow_data_dir }}/src/.env" }
  become: yes