- name: Find out if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ db_data_dir }}/pg_hba.conf"
  register: postgres_initialized
  
- name: Include Ubuntu specific installation
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include RedHat specific installation
  include_tasks: rhel.yml
  when: ansible_distribution == "RedHat"

- name: Listen on {{ db_server_listen }}
  ansible.builtin.lineinfile:
    path: "{{ db_data_dir }}/postgresql.conf"
    regexp: '^#listen_addresses ='
    line: "listen_addresses = '{{ db_server_listen }}'"
  
- name: Start and enable postgresql
  ansible.builtin.systemd: 
    name: postgresql-{{ version.postgresql }}
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"
  
# restart pgsql to make sure all new cfg is used
- name: Start and enable postgresql
  ansible.builtin.systemd: 
    name: postgresql
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"
  
- name: "Wait for Postgresql server ({{ groups['database'][0] }}) to become active"
  wait_for:
    host: "{{ groups['database'][0] }}"
    port: 5432
    delay: 5
    timeout: 60
  delegate_to: localhost
  connection: local

- name: Set postgres password
  postgresql_user:
      state: present
      name: postgres
      password: "{{ db_admin_password }}"
  become: yes
  become_user: postgres

