- name: Create OS group
  ansible.builtin.group:
    name: "{{ impala_os_group }}"
    state: present
  become: yes

- name: Include Create OS user
  include_role:
    name: create-system-user
  vars:
    new_user: "{{ impala_os_user }}"
    new_group: "{{ impala_os_group }}"

- name: Create configuration directory
  file:
    path: "{{ impala_etc_dir }}"
    state: directory
    mode: '0755'
  become: yes  

- name: Create Impala component directory
  file:
    path: "{{ stack_root }}/apache-impala-ubuntu-{{ version.impala }}/bin"
    state: directory
    owner: "{{ impala_os_user }}"
    group: "{{ impala_os_group }}"
    mode: '0755'
  become: yes  

- name: Create symlink latest Impala version
  file:
      src: "{{ stack_root }}/apache-impala-ubuntu-{{ version.impala }}"
      dest: "{{ stack_root }}/apache-impala-latest"
      state: link
  become: yes