
- name: Install required packages (Ubuntu)
  ansible.builtin.package:
    name:
      - libkrb5-dev
      - libsasl2-dev
      - libsasl2-2
      - libsasl2-modules-gssapi-mit
    state: latest
  become: yes
  when: ansible_distribution == 'Ubuntu'

# TODO: do we still need rhel-7-server-optional-rpms?
# - name: Enable rhel-7-server-optional-rpms (RHEL7)
#   shell: >
#     subscription-manager repos --enable=rhel-7-server-optional-rpms
#   become: yes  
#   when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Install required packages
  ansible.builtin.package:
    name:
      - python3-dev
      - python3-bitarray
    state: latest
  become: yes
  when: ansible_distribution == 'Ubuntu'
  
- name: Install required Python packages
  pip:
    name: 
      - kerberos
      - impala-shell
  become: yes
  when: ansible_distribution == 'Ubuntu'
  
# - name: Install required Python packages (RHEL)
#   pip:
#     name: 
#       - impala-shell
#   become: yes
#   when: ansible_distribution == 'RedHat'

# code below is for using the docker version of impala-shell
# prefer the pypi version, because for docker the user must have permission
# to run docker.

# - name: Create DockerFile
#   ansible.builtin.template:
#     src: "../templates/impala-shell_Dockerfile.j2"
#     dest: "{{ cache_root }}/apache-impala-ubuntu-{{ version.impala }}/impala-shell/Dockerfile"
#     mode: '0664'
#   delegate_to: localhost
#   connection: local
# 
# - name: Check if Docker image already exists
#   shell: "docker images | grep {{ groups['manager'][0] }}:{{ docker_registry_port }}/apache/impala-shell.*{{ version.impala }} | wc -l"
#   register: docker_img_exists
#   delegate_to: localhost
#   connection: local
#   become: yes
# 
# - name: Create Docker image on controller server
#   shell: >
#     cd {{ cache_root }}/apache-impala-ubuntu-{{ version.impala }}/impala-shell;
#     docker build -t apache/impala-shell:{{ version.impala }} .;
#     docker image tag apache/impala-shell:{{ version.impala }} {{ groups['manager'][0] }}:{{ docker_registry_port }}/apache/impala-shell:{{ version.impala }};
#   delegate_to: localhost
#   connection: local
#   when: docker_img_exists.stdout | int == 0
# 
# - name: Push Impala docker image to registry
#   shell: >
#     docker push {{ groups['manager'][0] }}:{{ docker_registry_port }}/apache/impala-shell:{{ version.impala }}
#   delegate_to: localhost
#   connection: local
#   when: docker_img_exists.stdout | int == 0
# 
# - name: Pull Impala image to host
#   shell: >
#     docker pull {{ groups['manager'][0] }}:{{ docker_registry_port }}/apache/impala-shell:{{ version.impala }}
# 
# - name: Create Container start script
#   ansible.builtin.template:
#     src: "../templates/impala-shell-cmd.j2"
#     dest: "{{ stack_root }}/apache-impala-latest/bin/impala-shell"
#     mode: '0755'
#   become: yes
