- name: Create OS group
  ansible.builtin.group:
    name: "{{ new_group }}"
    state: present
  become: yes
  
- name: Determine OS specific config (RHEL)
  set_fact:
     fact_login_shell: /sbin/nologin
  when: ansible_distribution == 'RedHat'
     
- name: Determine OS specific config (Ubuntu)
  set_fact:
     fact_login_shell: /usr/sbin/nologin
  when: ansible_distribution == 'Ubuntu'
  
- name: Create OS user
  ansible.builtin.user:
    name: "{{ new_user }}"
    group: "{{ new_group }}"
    shell: "{{ fact_login_shell }}"
    system: yes
  become: yes

# add user to group docker on gateway so user can start impala-shell container  
- name: Add user to group docker
  user:
    name: '{{ provision_user }}'
    groups: docker
    append: yes
  become: yes
  when: inventory_hostname in groups['gateway']