# OS user to run airflow docker container
airflow_os_user: airflow
airflow_os_group: airflow

# Location of airflow configuration files
airflow_etc_dir: "{{ config_root }}/airflow"
# Location of airflow logging
airflow_log_dir: /var/log/airflow

airflow_data_dir: /airflow

# Port airflow is listening on
airflow_web_port: 9990
airflow_flower_web_port: 9991

# www credentials
airflow_www_user: airflow
airflow_www_password:  "{{ vault_airflow_www_password }}"

# The airflow database options 
# Database will be create automatically
airflow_db: airflow_db
airflow_db_user: airflow
airflow_db_password: "{{ vault_airflow_db_password }}"

# Additional options
airflow_additional_cfg:
  # add additional config lines here
  # will be added to airflow.cfg
  core__default_timezone: 'Europe/Amsterdam'

  
  

