# On the management server a docker repository will be will deployed.
# Other cluster nodes will use this repository to download images

# port the docker registry will listen on 
docker_registry_port: 2000

# directory on hosts where docker data is stored
docker_data_dir: /var/lib/docker

# Docker installation repo
docker_repo:
  rhel79: "https://download.docker.com/linux/centos/7/$basearch/stable"

