# OS user to run superset
jupyterhub_os_user: jupyterhub
jupyterhub_os_group: jupyterhub

# Location of superset configuration files
jupyterhub_etc_dir: "{{ config_root }}/jupyterhub"
# Location of superset logging
jupyterhub_log_dir: /var/log/jupyterhub

# jupyterhub runs as a docker container,
# location of user data on host system
jupyterhub_data_dir: /data/jupyterhub

jupyterhub_port: 8000

# database options 
# database will be create automatically
jupyterhub_db: jupyterhub
jupyterhub_db_user: jupyterhub
jupyterhub_db_password: "{{ vault_jupyterhub_db_password }}"

# Additional options, thse are added to the jupyterhub config
jupyterhub_additional_cfg_block: |
  # add additional config lines here
  # see url below for available options
  #