minio_os_user: minio-user

minio_os_group: minio-user

# location of config files
minio_etc_dir: "{{ config_root }}/minio"

minio_log_dir: /var/log/minio

minio_root_user: admin
minio_root_password: {{ vault_minio_password }}

minio_console_listen_port: 9001

minio_disk: 
  - /data/1/minio
  - /data/2/minio
  - /data/3/minio
  
minio_volumes: 'https://hadoop-dev{1...3}.{{ dns_domainname }}:9000/data/{1...3}/minio'

minio_download_url: 'https://dl.min.io/server/minio/release/linux-amd64/archive/{{ version.minio }}_amd64.deb'