# Monitor server will get Prometheus and Grafana docker images deployed.

#Prometheus
prometheus_etc_dir: "{{ config_root }}/prometheus"
prometheus_data_dir: /data/prometheus
prometheus_port: 9090

prometheus_user: admin
# Prometheus admin password
prometheus_password: "{{ vault_prometheus_password }}"

#URL where to download the JMX exporter for Proemtheus
prometheus_jmx_exporter_url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar"

# Grafana
grafana_etc_dir: "{{ config_root }}/grafana"
grafana_port: 3000
grafana_admin_user: admin
# Grafana admin password
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# database for grafana, create automatically
grafana_db_name: grafana
grafana_db_user: grafana
# Grafana database password
grafana_db_password: "{{ vault_grafana_db_password }}"

# Additional options, these are added to the grafana.ini config file
grafana_additional_cfg_block: |
  # add additional config lines here
  # will be added to grafana.ini
