# directory on cluster nodes where to keep tls files
tls_etc_dir: "{{ config_root }}/tls"

# location of pem file with cert chain and file with key
# this is location on the manager node (where ansible playbook are executed)
tls_cert:
  # pem file with cert and all required intermediate certs
  crt: ~/tls/star.sidnlabs.nl.chain.pem 
  # key file also in pem format
  key: ~/tls/star.sidnlabs.nl.key

# Password for the truststore (tls_remote_truststore) that will be created on the
# nodes and is used by multiple services
tls_remote_truststore_password: "{{ vault_tls_remote_truststore_password }}"

# DO NOT NEED TO CHANGE ANYTHING BELOW HERE

# Java truststore containing all certs and the private key
# NO NEED TO CHANGE THIS.
tls_remote_truststore: hadoop-tls.jks

# new name of the tls_cert.crt on the cluster nodes
# NO NEED TO CHANGE THIS.
tls_remote_pub_chain: hadoop_tls_pub_chain.pem

# new name of the tls_cert.key on the cluster nodes
# NO NEED TO CHANGE THIS.
tls_remote_priv_key: hadoop_tls_priv.key
