# Start standby name node, there are multiple start modes available here:
# 1 Start unchanged cluster normal
# 2 Initialize and start a new hdfs cluster    
# 3 Upgrade and start an existing cluster

# Bootstrap Standby namenode for new HDFS fs
- name: Bootstrap Standby namenode
  shell: >
      . {{ hadoop_etc_dir }}/hadoop-env.sh;
      {{ stack_root }}/hadoop-latest/bin/hdfs namenode -bootstrapStandby -force -nonInteractive
  become_user: "{{ hadoop_os_user.hdfs }}"
  when: reg_new.stat.exists and not reg_upgrade.stat.exists
  
# if not Initializing new cluster or upgrading an existing cluster 
# then do a normal start of the existing cluster.
- name: Start name node
  ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: hdfs_namenode

# start failover Controller on name node
- name: Start ZK Failover Controller daemon
  ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: hdfs_zkfc


