- name: Create config directory
  file:
    path: "{{ mgtm_console_content_dir }}/client-config"
    state: directory
    mode: '0775'
    
- name: Create client config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ mgtm_console_content_dir }}/client-config/{{ item | basename | replace('.j2', '') }}"
    mode: '0644'
  loop:
    - ../../roles/hadoop-config/templates/core-site.xml.j2
    - ../../roles/hadoop-config/templates/hdfs-site.xml.j2
    - ../../roles/hadoop-config/templates/yarn-site.xml.j2
    - ../../roles/hadoop-config/templates/ssl-client.xml.j2
    - ../../roles/hive-config/templates/hive-site.xml.j2
    - ../../roles/kerberos-kdc-config/templates/krb5.conf.j2
    
- name: Delete old archive
  ansible.builtin.file:
    path: "{{ mgtm_console_content_dir }}/client-config/client-config.tar.gz"
    state: absent

- name: Create a gz archive of config files
  community.general.archive:
    path:
    - "{{ mgtm_console_content_dir }}/client-config"
    dest: "{{ mgtm_console_content_dir }}/client-config/client-config.tar.gz"
