- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ superset_os_user }}"
    group: "{{ superset_os_group }}"
  loop:
    - '{{ superset_etc_dir }}/python_path'
  become: yes  
  
- name: Create config files
  ansible.builtin.template:
    src: templates/{{ item }}
    dest: '{{ superset_etc_dir }}/{{ item | replace('.j2','') }}'
    owner: "{{ superset_os_user }}"
    group: "{{ superset_os_group }}"
  loop:
    - ngingx-proxy.conf.j2
    - superset.env.j2
  become: yes

- name: Create secret key
  shell: >
      cat {{ superset_etc_dir }}/secret_key
  register: reg_secret_key
  
- set_fact:
    fact_secret_key: "{{ reg_secret_key.stdout }}"
    
- name: Copy config python script
  ansible.builtin.template:
    src: templates/superset_config.py.j2
    dest: '{{ superset_etc_dir }}/python_path/superset_config.py.j2'
  become: yes
  
- name: Create docker-compose script
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: '{{ stack_root }}/apache-superset-{{ version.superset }}/docker-compose.yml'
  become: yes
