- name: Check if jupyterhub db exists
  postgresql_query:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      query: >
        SELECT datname 
        FROM pg_database
        WHERE datname = '{{ jupyterhub_db }}'
  delegate_to: localhost
  connection: local
  
- name: Create jupyterhub db user
  postgresql_user:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      state: present
      name: "{{ jupyterhub_db_user }}"
      password: "{{ jupyterhub_db_password }}"
  delegate_to: localhost
  connection: local

- name: Create jupyterhub database
  postgresql_db:
      login_host: "{{ groups['database'][0] }}"
      login_password: "{{ db_admin_password }}"
      login_user: postgres
      owner: "{{ jupyterhub_db_user }}"
      state: present
      name: "{{ jupyterhub_db }}"
  delegate_to: localhost
  connection: local

  