- name: Create OS group
  ansible.builtin.group:
    name: "{{ jupyterhub_os_group }}"
    state: present
  become: yes
  
- name: Include Create OS user
  include_role:
    name: create-system-user
  vars:
    new_user: "{{ jupyterhub_os_user }}"
    new_group: "{{ jupyterhub_os_group }}"
    
- name: Add user to group docker
  user:
    name: '{{ jupyterhub_os_user }}'
    groups: docker
    append: yes
  become: yes
    
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jupyterhub_os_user }}"
    group: "{{ jupyterhub_os_group }}"
  loop:
    - '{{ jupyterhub_etc_dir }}'
    - '{{ jupyterhub_log_dir }}'
  become: yes
  
  
- name: Create Jupyterhub component directory
  file:
    path: "{{ stack_root }}/jupyterhub-{{ version.jupyterhub }}/bin"
    state: directory
    owner: "{{ jupyterhub_os_user }}"
    group: "{{ jupyterhub_os_group }}"
    mode: '0755'
  become: yes  

- name: Create symlink latest Jupyterhub version
  file:
      src: "{{ stack_root }}/jupyterhub-{{ version.jupyterhub }}"
      dest: "{{ stack_root }}/jupyterhub-latest"
      state: link
  become: yes
  
- name: Create Systemd unit
  ansible.builtin.template:
    src: ../templates/{{ item }}
    dest: /etc/systemd/system/{{ item | replace('.j2','') }}
  loop:
    - jupyterhub.service.j2
  become: yes
  
- name: Include create database
  include_tasks: tasks/database.yml
  
- name: Include build docker image 
  include_tasks: tasks/docker-build.yml
  
- name: Create Container start script
  ansible.builtin.template:
    src: "../templates/{{ item }}"
    dest: "{{ stack_root }}/jupyerhub-latest/bin/{{ item | replace('.j2','') }}"
    mode: '0755'
    owner: "{{ jupyterhub_os_user }}"
    group: "{{ jupyterhub_os_group }}"
  become: yes
  loop:
    - start-jupyerhub.sh.j2
    - stop-jupyerhub.sh.j2

- name: Systemctl Reload Daemons
  shell: systemctl daemon-reload
  become: yes  
  