# (re)enable the Ranger plugin for HDFS.
# after updating the TLS certificate for Ranger Admin the Ranger plugin for HDFS
# may not be able to connect to  Ranger Admin anymore untile the plugin is re-enabled.
  
# - name: Check if htrace jar is already on management node
#   stat:
#     path: "{{ download_root }}/{{ ranger_download_url.htrace | basename }}"
#   register: stat_download_jar
#   delegate_to: localhost
#   connection: local
# 
# - name: Download new htrace jar
#   get_url:
#       url: "{{ ranger_download_url.htrace }}"
#       dest: "{{ download_root }}"
#   when: not stat_download_jar.stat.exists
#   delegate_to: localhost
#   connection: local
# 
# - name: Fix missing htrace class, copy correct jar to remote
#   copy:
#       src: "{{ download_root }}/{{ ranger_download_url.htrace | basename }}"
#       dest: "{{ stack_root }}/ranger-hdfs-plugin-latest/install/lib/"
#   become: yes
# 

- name: Include add libs
  include_tasks: ranger-hdfs-plugin-libs.yml

- name: Enable Ranger for HDFS
  shell: >
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))));
    cd {{ stack_root }}/ranger-hdfs-plugin-latest/;
    ./enable-hdfs-plugin.sh
  become: yes
