# enable cgroups v1 on ubuntu 22.04 yarn does not work with v2
- name: Check if cgroup v1 is enabled
  lineinfile: 
    state: absent
    path: /etc/default/grub
    regexp: "systemd.unified_cgroup_hierarchy=0"
  check_mode: yes
  register: grub_cfg
  changed_when: false
  
- name: Remove old Grub cgroup config
  replace:
    path: /etc/default/grub
    regexp: 'systemd.unified_cgroup_hierarchy=[0-9]'
    replace: ''
  become: yes
  when: grub_cfg.found == 0
    
- name: Set Grub cgroup config for cgroups v1
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 systemd.unified_cgroup_hierarchy=0"'
    backrefs: true
  become: yes
  when: grub_cfg.found == 0

- name: Update Grub
  shell: update-grub
  become: yes
  when: grub_cfg.found == 0

- name: Reboot server
  shell: >
    sleep 2 && shutdown -r now "Ansible reboot"
  async: 1 
  poll: 0
  ignore_errors: true
  become: yes
  when: grub_cfg.found == 0

- name: "Wait for server ({{ inventory_hostname }})"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 10
    timeout: 600
  delegate_to: localhost
  connection: local
  run_once: true
  when: grub_cfg.found == 0
