# create py-env on all worker nodes
- hosts: gateway:hadoop
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    
    - name: Copy requirements file
      ansible.builtin.copy:
        src: "{{ py_env_req_file }}"
        dest: "{{ cache_root }}/{{ py_env_req_file | basename }}"
      when: py_env_req_file is defined

    - name: Include role for Python create venv
      include_role:
        name: python-venv
