# create py-env on all worker nodes
- hosts: gateway:hadoop
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    
    - name: Include role for Python create venv
      include_role:
        name: python-venv
