# create Kerberos user  
- hosts: all:!manager
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop.yml"
  remote_user: hadoop-mgr
  tasks:
      # Create new uer in kerberos database
    - name: Delete directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ download_root }}"
        - "{{ config_root }}"
        - "{{ cache_root }}"
        - "{{ stack_root }}"
        - "{{ hadoop_dfs_datanode_data_dir }}"


