- hosts: database
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/db_vars.yml"
  become: yes
  remote_user: hadoop-mgr
  tasks:
    - name: Include component deploy
      include_role:
        name: database
      when: (not db_use_existing) and (var_deploy_comp | bool)
