# copy tls matarial to all nodes, except the gateway nodes.
- hosts: all
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
    - "{{ prov_cfg_dir }}/vars/db_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Include component deploy
      include_role:
        name: tls
      # do not install tls material on dedicated db server
      when: not (inventory_hostname in groups['database'] and db_use_existing)
