- hosts: console
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hive_vars.yml"
    - "{{ prov_cfg_dir }}/vars/console_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hue_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/livy_vars.yml"
    - "{{ prov_cfg_dir }}/vars/spark_vars.yml"
    - "{{ prov_cfg_dir }}/vars/iceberg_vars.yml"
  remote_user: hadoop-mgr
  become: yes
  roles:
    - client-config
