# deploy prometheus end proxy on each impala node 
- hosts: all
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/monitor_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Include component deploy
      include_role:
        name: monitor-proxy
      when: var_deploy_comp | bool
    
    - name: Include configuration deploy
      include_role:
        name: monitor-proxy-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool)
