# ranger must know about superset user, create superset on
# ranger server so it can be detected by ranger usersync
- hosts: ranger
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/superset_vars.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Include Create superset user on Ranger server
      include_role:
        name: create-system-user
      vars:
        new_user: "{{ superset_os_user }}"
        new_group: "{{ ranger_sync_group_name }}"
      when: (var_deploy_comp | bool) and (groups['superset'] | length > 0)
        
- hosts: superset
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
    - "{{ prov_cfg_dir }}/vars/db_vars.yml"
    - "{{ prov_cfg_dir }}/vars/docker_vars.yml"
    - "{{ prov_cfg_dir }}/vars/superset_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Include component deploy
      include_role:
        name: docker
      when: var_deploy_comp | bool
    
    - name: Include configuration deploy
      include_role:
        name: docker-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool)
            
    - name: Include component deploy
      include_role:
        name: superset
      when: var_deploy_comp | bool
    
    - name: Include configuration deploy
      include_role:
        name: superset-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool)    
