- hosts: impala:impala_statestore:impala_catalog:gateway
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hive_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hue_vars.yml"
    - "{{ prov_cfg_dir }}/vars/livy_vars.yml"
    - "{{ prov_cfg_dir }}/vars/spark_vars.yml"
  remote_user: hadoop-mgr
  tasks:
      # shared config must always be generated before config deploy
      # the gateway node is an exception, this host does not need impala config
    - name: Include component deploy
      include_role:
        name: shared-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool) 
            and inventory_hostname not in groups['gateway']
      
    - name: Include component deploy
      include_role:
        name: impala
      when: var_deploy_comp | bool
    
    - name: Include configuration deploy
      include_role:
        name: impala-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool)    
            
- hosts: impala_ha_proxy
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
  remote_user: hadoop-mgr
  tasks:  
    - name: Include component deploy
      include_role:
        name: impala-proxy
      when: var_deploy_comp | bool
    
    - name: Include configuration deploy
      include_role:
        name: impala-proxy-config
      when: (var_deploy_comp | bool) or (var_deploy_cfg_only | bool)    

  