- hosts: all:!manager
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/nexpose.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Include component deploy
      include_role:
        name: soc_nexpose
      when: var_deploy_comp | bool
    