- hosts: impala:impala_statestore:impala_catalog:gateway
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hive_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/tls_vars.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hue_vars.yml"
    - "{{ prov_cfg_dir }}/vars/livy_vars.yml"
    - "{{ prov_cfg_dir }}/vars/spark_vars.yml"
    - "{{ prov_cfg_dir }}/vars/docker_vars.yml"
  remote_user: hadoop-mgr
  tasks:      
    - name: Include component deploy
      include_role:
        name: impala-shell
      when: var_deploy_comp | bool
