
- hosts: all
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
  remote_user: hadoop-mgr
  tasks:

    - name: Delete directories
      vars:
         dirs:
           - "{{ download_root }}"
           - "{{ config_root }}"
           - "{{ cache_root }}"
           - "{{ stack_root }}"
           - "{{ hadoop_dfs_datanode_data_dir }}"
           - "{{ hadoop_dfs_namenode_name_dir }}"
           - "{{ hadoop_dfs_namenode_checkpoint_dir }}"
           - "{{ hadoop_dfs_journalnode_edits_dir }}"
           - "{{ yarn_node_manager_logdir }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ dirs | flatten }}"
        
      become: yes
      



