- hosts: hadoop:hdfs_nn:hdfs_journalnode:hdfs_httpfs:yarn_resource_mgr:yarn_timelineserver
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
  remote_user: hadoop-mgr
  tasks:

    - name: Delete directories
      vars:
         dirs:
           - "{{ hadoop_dfs_datanode_data_dir }}"
           - "{{ hadoop_dfs_namenode_name_dir }}"
           - "{{ hadoop_dfs_namenode_checkpoint_dir }}"
           - "{{ hadoop_dfs_journalnode_edits_dir }}"
           - "{{ yarn_node_manager_logdir }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ dirs | flatten }}"
      become: yes
  