- hosts: hdfs_nn
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/hadoop_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
  remote_user: hadoop-mgr
  tasks:
    - name: Enable Ranger HDFS plugin
      include_tasks: ../roles/hadoop/tasks/ranger-hdfs-plugin-enable.yml