- hosts: airflow
  vars_files:
    - "{{ prov_cfg_dir }}/vars/airflow_vars.yml"
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: airflow
  tasks:
    - name: "Start service(s)"
      include_tasks: startup/tasks/generic-service.yml
