- hosts: superset
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
  become: yes
  tasks:
    - name: Start superset service
      include_tasks: startup/tasks/generic-service.yml    
      loop: 
        - superset
        - superset-kt-renewer.timer
      loop_control:
        loop_var: service_name  
