- hosts: jupyterhub
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: jupyterhub
  tasks:
    - name: "Start {{ service_name }}"
      include_tasks: startup/tasks/generic-service.yml
