- hosts: spark_history
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/spark_vars.yml"
    - "{{ prov_cfg_dir }}/vars/kerberos_vars.yml"
  tasks:
    - name: Create Spark HDFS directories
      ansible.builtin.shell: "{{ stack_root }}/apache-spark-latest/bin/create-hdfs-dir.sh"
      become: yes
      
    - name: Upload Spark libraries to HDFS
      ansible.builtin.shell: "{{ stack_root }}/apache-spark-latest/bin/upload-spark-jars.sh"
      become: yes

    - name: Start {{ service_name }}
      vars:
        service_name: spark_historyserver
      include_tasks: startup/tasks/generic-service.yml
      
      
- hosts: spark_thrift
  remote_user: hadoop-mgr
  become: yes
  tasks:    
    - name: Start {{ service_name }}
      vars:
        service_name: spark_thrift
      include_tasks: startup/tasks/generic-service.yml 
      