- hosts: impala_statestore
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_statestored
  tasks:
    - name: "Start {{ service_name }}"
      include_tasks: startup/tasks/generic-service.yml
      
- hosts: impala_catalog
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_catalogd
  tasks:
    - name: "Start {{ service_name }}"
      include_tasks: startup/tasks/generic-service.yml
      
- hosts: impala
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_impalad
  tasks:
    - name: "Start {{ service_name }}"
      include_tasks: startup/tasks/generic-service.yml
    
- hosts: impala
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/impala_vars.yml"
  become: yes
  tasks:      
    - name: Set Impala executor cgroup cpu-shares
      shell: >
          systemctl set-property impala_impalad.service CPUShares={{ impala_cgroups.cpu_shares.impalad }}
      when: ('hadoop' in groups and inventory_hostname in groups['hadoop'])
          
- name: Impala Proxy
  import_playbook: start-impala-proxy.yml
