- hosts: minio
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/vault_password_vars.yml"
    - "{{ prov_cfg_dir }}/vars/minio_vars.yml"
  become: yes
  vars:
    service_name: minio
  tasks:      
    - name: Start {{ service_name }}
      include_tasks: startup/tasks/generic-service.yml     


 
