- hosts: superset
  remote_user: hadoop-mgr
  become: yes
  # vars:
  #   service_name: superset
  tasks:
    - name: Start superset service
      include_tasks: startup/tasks/generic-service.yml    
      loop: 
        - superset
        - superset-kt-renewer.timer
      loop_control:
        loop_var: service_name  
        
    # make sure to create a kerberos session 
    # the sesson will be extended periodically by the kt-renewer
    - name: Create Kerberos session
      shell: >
        {{ stack_root }}/apache-superset-latest/bin/superset-kt-renewer.sh
      become: yes