- hosts: zookeeper
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: zookeeper
  tasks:
    - name: "Start {{ service_name }}"
      include_tasks: startup/tasks/generic-service.yml
  

