- hosts: impala_statestore
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_statestored
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      
- hosts: impala_catalog
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_catalogd
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      
- hosts: impala
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_impalad
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml


- name: Impala Proxy
  import_playbook: stop-impala-proxy.yml


