- hosts: hive
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop {{ service_name }}"
      vars:
        service_name: hive_metastore
      include_tasks: shutdown/tasks/generic-service.yml
