- hosts: impala_statestore
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_statestored
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml
      
- hosts: impala_catalog
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_catalogd
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml
      
- hosts: impala
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_impalad
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml


- hosts: impala_ha_proxy
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: Stop haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: stopped

