- hosts: impala
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      loop: 
        - impala_prometheus_proxy_impalad
        - prometheus_impala_proxy_kill.timer
      loop_control:
        loop_var: service_name  
        
- hosts: impala_catalog
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      loop: 
        - impala_prometheus_proxy_catalogd
        - prometheus_impala_proxy_kill.timer
      loop_control:
        loop_var: service_name  
        
- hosts: impala_statestore
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      loop: 
        - impala_prometheus_proxy_statestored
        - prometheus_impala_proxy_kill.timer
      loop_control:
        loop_var: service_name  
      
- hosts: all
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml
      loop: 
        - prometheus-node-exporter
        - prometheus-port-monitor.timer
      loop_control:
        loop_var: service_name  
