- hosts: monitor
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml    
      loop: 
        - prometheus
        - grafana
      loop_control:
        loop_var: service_name
