- hosts: impala
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_prometheus_proxy_impalad
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml
        
- hosts: impala_catalog
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_prometheus_proxy_catalogd
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml
        
- hosts: impala_statestore
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: impala_prometheus_proxy_statestored
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml
      
- hosts: all
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: prometheus_node_exporter
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml