# only stop db that is part of the cluster
# an existing external db must be stopped out of bounds
- hosts: database
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: Start and enable postgresql
      ansible.builtin.systemd: 
        name: postgresql-{{ version.postgresql }}
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
      
    - name: Start and enable postgresql
      ansible.builtin.systemd: 
        name: postgresql
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"