# cannot access variables at the import_playbook level.
# us trick below to read the db_use_existing variable anyway 
- hosts: manager
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/db_vars.yml"
  tasks:
   - set_fact:
        should_start_db: '{{ not db_use_existing }}'
     delegate_to: localhost
     delegate_facts: yes
     
- name: Monitor
  import_playbook: stop-monitor.yml
  
- name: Monitor Proxies
  import_playbook: stop-monitor-proxy.yml
  
- name: Spark
  import_playbook: stop-spark.yml
  
- name: Yarn
  import_playbook: stop-yarn.yml
  
- name: HDFS
  import_playbook: stop-hdfs.yml

- name: Zookeeper
  import_playbook: stop-zookeeper.yml
    
- name: Hive
  import_playbook: stop-hive.yml

- name: Impala
  import_playbook: stop-impala.yml
  
- name: Impala Proxy
  import_playbook: stop-impala-proxy.yml
       
- name: Hue
  import_playbook: stop-hue.yml
  
- name: Jupyterhub
  import_playbook: stop-jupyterhub.yml
  
- name: Superset
  import_playbook: stop-superset.yml
  
- name: Livy
  import_playbook: stop-livy.yml
  
- name: Ranger
  import_playbook: stop-ranger.yml
  
- name: Solr
  import_playbook: stop-solr.yml
  
- name: MGMT Console
  import_playbook: stop-console.yml
  
- name: Docker Registry UI
  import_playbook: stop-docker-reg-ui.yml
  
- name: Database
  import_playbook: stop-db.yml
  when: hostvars.localhost.should_start_db
  
- name: Kerberos
  import_playbook: stop-krb-kdc.yml