- hosts: superset
  remote_user: hadoop-mgr
  become: yes
  tasks:
    - name: Stop superset service
      include_tasks: shutdown/tasks/generic-service.yml    
      loop: 
        - superset
        - superset-kt-renewer.timer
      loop_control:
        loop_var: service_name  
        