- hosts: minio
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/minio_vars.yml"
  become: yes
  vars:
    service_name: minio
  tasks:
    - name: "Stop service(s)"
      include_tasks: shutdown/tasks/generic-service.yml           

 
