- hosts: zookeeper
  remote_user: hadoop-mgr
  become: yes
  vars:
    service_name: zookeeper
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml        