- hosts: ranger
  remote_user: hadoop-mgr
  vars_files:
    - "{{ prov_cfg_dir }}/vars/all.yml"
    - "{{ prov_cfg_dir }}/vars/ranger_vars.yml"
  become: yes
  tasks:
    - name: "Stop {{ service_name }}"
      include_tasks: shutdown/tasks/generic-service.yml    
      loop: 
        - ranger_admin
        - ranger_usersync
      loop_control:
        loop_var: service_name  

 
