{
 "title": "Hadoop - HDFS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_NumLiveDataNodes)"
    }
   ]
  },
  {
   "title": "DFS Block Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_BlocksTotal{ name=\"FSNamesystem\"})"
    }
   ]
  },
  {
   "title": "DFS File Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_FilesTotal)"
    }
   ]
  },
  {
   "title": "DFS Bytes Written (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(Hadoop_DataNode_BytesWritten[24h]))"
    }
   ]
  },
  {
   "title": "DFS Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_CapacityTotal)"
    }
   ]
  },
  {
   "title": "DFS Capacity Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_CapacityUsed)"
    }
   ]
  },
  {
   "title": "DFS Capacity Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NameNode_CapacityRemaining)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "DFS Used",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DFS Bytes Written (1h)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_BytesWritten[1h])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data Node Block Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_BlocksRead[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DFS Blocks Written (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_BlocksWritten[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Name node Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "Hadoop_NameNode_MemHeapUsedM", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "DFS Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\"} / Hadoop_DataNode_Capacity{name=\"FSDatasetState\"} ) * 100.0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data Node Remote Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_RemoteBytesRead[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data Node Block Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_BlocksWritten[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data node Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "Hadoop_DataNode_MemHeapUsedM", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}