{
 "title": "Hadoop - Yarn",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_ContainersRunning)"
    }
   ]
  },
  {
   "title": "Available VCores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NodeManager_AvailableVCores)"
    }
   ]
  },
  {
   "title": "Allocated VCores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_NodeManager_AllocatedVCores)"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AvailableGB)"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node Manager Available Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Hadoop_NodeManager_AvailableGB", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainerCpuUtilization",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainerUsedMemGB",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(Hadoop_NodeManager_ContainersCompleted[1m]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(delta(Hadoop_NodeManager_ContainersFailed[1m]))",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}