{
 "title": "Node - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU load 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU load 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load15{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes )) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    },
    {}
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    },
    {}
   ]
  }
 ]
}