# create jks truststore, used by hdfs namenode (ssl-server.xml)
- name: Run JKS script
  shell: "{{ tls_etc_dir }}/create-jks.sh"
  become: yes

- name: Install Haproxy TLS
  import_tasks: ha-proxy.yml
  become: yes
  when: inventory_hostname in groups['impala_ha_proxy']
        
- name: Install Ranger Admin TLS
  import_tasks: ranger-admin.yml
  become: yes
  when: inventory_hostname in groups['ranger']
  
- name: Install Ranger Plugin TLS
  import_tasks: ranger-plugin.yml
  become: yes
  when: (inventory_hostname in groups['impala']) 
    or (inventory_hostname in groups['impala_catalog']) 
    or (inventory_hostname in groups['hadoop']) 
    or (inventory_hostname in groups['hdfs_primary_nn']) 
    or (inventory_hostname in groups['hdfs_secondary_nn']) 

- name: Install Monitor TLS
  import_tasks: monitor.yml
  become: yes
  when: inventory_hostname in groups['monitor']
