- name: Create Docker configuration files
  ansible.builtin.template:
    src: "../templates/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { "src": "docker_daemon.json.j2", "dest": "/etc/docker/daemon.json"}
  become: yes
  