- name: test local action
  shell: echo "working"
  delegate_to: localhost
  run_once: true
  
- name: Check if the MinIO is already downloaded
  stat:
    path: "{{ download_root }}/{{ version.minio }}_amd64.deb"
  register: stat_minio_src
  delegate_to: localhost
  connection: local
  run_once: true
  
- name: Download MinIO.
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ download_root }}"
    force: false
  delegate_to: localhost
  connection: local
  run_once: true
  when: not stat_minio_src.stat.exists

- name: Check if the MinIO src is already on remote
  stat:
    path: "{{ cache_root }}/{{ version.minio }}_amd64.deb"
  register: stat_remote_minio_src

- name: Copy MinIO to remote
  ansible.builtin.copy:
    src: "{{ download_root }}/{{ version.minio }}_amd64.deb"
    dest: "{{ cache_root }}"
    mode: '0644'
  when: not stat_remote_minio_src.stat.exists
  
- name: Install MinIO package
  shell: >
    dpkg -i {{ cache_root }}/{{ version.minio }}_amd64.deb
  become: yes

- name: Enable MinIO systemd daemon
  systemd:
    name: minio
    enabled: yes
    daemon_reload: true
  become: yes
