- name: Hadoop configuration
  ansible.builtin.template:
    src: "../templates/{{ item.name }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.perm }}"
    owner: root
    group: "{{ hadoop_os_group }}"
  loop:
    - { name: 'hdfs-site.xml.j2', dest: '{{ hadoop_etc_dir }}/hdfs-site.xml', perm: '0644' }
   become: yes
