- name: Systemctl Reload Daemons
  shell: systemctl stop prometheus_node_exporter
  become: yes 

- name: create Prometheus config directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ prometheus_etc_dir }}"
    - "{{ prometheus_etc_dir }}/metrics"
  become: yes
  
- name: Create Prometheus Node Exporter password hash 
  shell: >
    echo "{{ prometheus_node_exporter_password }}" | htpasswd -niBC 10 "" | tr -d ':\n'
  register: prometheus_node_exporter_password_hash
  
- name: Create Node Exporter configuration files
  ansible.builtin.template:
    src: ../templates/{{ item }}
    dest: "{{ prometheus_etc_dir }}/{{ item | replace('.j2', '') }}"
    mode: '0644'
  loop:
    - prometheus-node-exporter-config.yml.j2
  become: yes
  
- name: Create Node Exporter static metric files
  ansible.builtin.template:
    src: ../templates/{{ item }}
    dest: "{{ prometheus_etc_dir }}/metrics/{{ item | replace('.j2', '') }}"
    mode: '0644'
  loop:
    - roles.prom.j2
  become: yes
    
- name: Create Impala Proxy configuration files
  ansible.builtin.template:
    src: "../templates/prometheus-proxy-env.sh.j2"
    dest: "{{ impala_etc_dir }}/prometheus-proxy-env-{{ daemon.name }}.sh"
    mode: '0755'
    owner: "{{ impala_os_user }}"
    group: "{{ impala_os_group }}"
  loop:
    - { name: 'impalad', group: 'impala' }
    - { name: 'catalogd', group: 'impala_catalog' }
    - { name: 'statestored', group: 'impala_statestore' }
  loop_control:
    loop_var: daemon
  become: yes
  when: inventory_hostname in groups[daemon.group] 