- name: create Prometheus config directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ prometheus_etc_dir }}"
  become: yes
  
- name: install required packages (RHEL)
  ansible.builtin.package:
    name:
      - httpd-tools
    state: latest
  become: yes
  when: ansible_distribution == 'RedHat'
    
- name: install required packages (Ubuntu)
  ansible.builtin.package:
    name:
      - apache2-utils
    state: latest
  become: yes
  when: ansible_distribution == 'Ubuntu'
  
- name: Create Prometheus Node Exporter password hash 
  shell: >
    echo "{{ prometheus_node_exporter_password }}" | htpasswd -niBC 10 "" | tr -d ':\n'
  register: prometheus_node_exporter_password_hash
  
- name: Create Node Exporter configuration file
  ansible.builtin.template:
    src: "../templates/prometheus-node-exporter-config.yml.j2"
    dest: "{{ prometheus_etc_dir }}/prometheus-node-exporter-config.yml"
    mode: '0644'
  become: yes
    
- name: Create Impala Proxy configuration files
  ansible.builtin.template:
    src: "../templates/prometheus-proxy-env.sh.j2"
    dest: "{{ impala_etc_dir }}/prometheus-proxy-env-{{ daemon.name }}.sh"
    mode: '0755'
    owner: "{{ impala_os_user }}"
    group: "{{ impala_os_group }}"
  loop:
    - { name: 'impalad', group: 'impala' }
    - { name: 'catalogd', group: 'impala_catalog' }
    - { name: 'statestored', group: 'impala_statestore' }
  loop_control:
    loop_var: daemon
  become: yes
  when: inventory_hostname in groups[daemon.group] 