- name: Update APT cache
  apt:
    update_cache: yes
  become: yes
    
- name: Install required packages
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present    
  become: yes

- name: Add the GPG key for the official Docker repository
  shell: >
      curl -fsSL {{ docker_repo.ubuntu }}/gpg | sudo apt-key add -;
      add-apt-repository -y "deb [arch=amd64] {{ docker_repo.ubuntu }} focal stable"
  become: yes

- name: Install Docker packages
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest
    update_cache: yes
  become: yes

