- name: Add Docker-CE stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: "{{ docker_repo.rhel79 }}"
  become: yes
  
- name: Add signing key
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/centos/gpg"
    state: present
    
- name: Remove conflicting container packages
  ansible.builtin.package:
    name:
      - podman
      - buildah
    state: absent
  become: yes
  
# RHEL 7.9 deps
- name: Install older dependencies for Docker on RHEL 7.9
  ansible.builtin.shell: |
    yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.119.2-1.911c772.el7_8.noarch.rpm
    yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/slirp4netns-0.4.3-4.el7_8.x86_64.rpm
    yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm  
  become: yes
  ignore_errors: yes 
  when: >
   (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") 
    
- name: install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest
  become: yes
