- name: Populate service facts
  service_facts:

- debug:
    msg: "Docker installed: {{ 'docker' in services }}"
  
- name: Install Docker Python dependencies
  pip:
    name:
      - requests
      - docker
  become: yes
    
- name: Mak sure Docker service is running
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  when: "'docker' in services"

- name: Create docker cfg directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: yes
  when: not 'docker' in services
  
- name: Create docker data directory
  file:
    path: "{{ docker_data_dir }}"
    state: directory
  become: yes
  
- name: Include Docker installation (RHEL)
  include_tasks: tasks/docker-redhat.yml
  when: (ansible_distribution == "RedHat") 
        and not 'docker' in services
  
- name: Include Docker installation (Ubuntu)
  include_tasks: tasks/docker-ubuntu.yml
  when: (ansible_distribution == "Ubuntu") 
         and not 'docker' in services

- name: Add user '{{ provision_user }}' to group docker
  user:
    name: '{{ provision_user }}'
    groups: docker
    append: yes
  become: yes
  
- name: Reset ssh connection to allow group changes to affect 'current login user'
  meta: reset_connection

- name: Systemctl Reload Daemons
  command: systemctl daemon-reload
  become: yes
  when: not 'docker' in services
  
- name: Enable and start service Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  when: not 'docker' in services