- name: Install Docker Python dependencies
  pip:
    name:
      - requests
      - docker
  become: yes
  
- name: Check if Docker is already present
  shell: command -v docker >/dev/null 2>&1
  register: is_docker_exist
  ignore_errors: yes
  
- name: "Print result of check: Docker already present"
  ansible.builtin.debug:
    msg: Docker already present: {{ is_docker_exist.rc == 0 }}

- name: Create docker cfg directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: yes
  when: is_docker_exist.rc == 1
  
- name: Include Docker installation (RHEL)
  include_tasks: tasks/docker-redhat.yml
  when: (ansible_distribution == "RedHat") 
        and ( is_docker_exist.rc == 1)
  
- name: Include Docker installation (Ubuntu)
  include_tasks: tasks/docker-ubuntu.yml
  when: (ansible_distribution == "Ubuntu") 
         and ( is_docker_exist.rc == 1)

- name: Add user '{{ provision_user }}' to group docker
  user:
    name: '{{ provision_user }}'
    groups: docker
    append: yes
  become: yes
  
- name: Reset ssh connection to allow group changes to affect 'current login user'
  meta: reset_connection

- name: Systemctl Reload Daemons
  command: systemctl daemon-reload
  become: yes
  
- name: Enable service Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
  become: yes